version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "testJuliaDeploy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11sntr6wfkimd"
s3_prefix = "testJuliaDeploy"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["JuliaFunction=995952994537.dkr.ecr.us-east-1.amazonaws.com/testjuliadeploy068f6b91/juliafunctioncfb9909arepo"]
